---
- name: Create trajectory directory
  file:
    path: "{{ project_dir }}/{{ trajectory.trajectory }}/output"
    state: directory
    recurse: yes
    mode: 0755
  run_once: yes

- name: Create analysis directory
  file:
    path: "{{ project_dir }}/{{ trajectory.trajectory }}/analysis"
    state: directory
    recurse: yes
    mode: 0755
  run_once: yes

- name: Create NAMD configuration files
  template:
    src: "{{ trajectory.config_template }}"
    dest: "{{ trajectory_dir }}/abf_quench{{ item.batch }}.namd"
    mode: 0644
  loop: "{{ trajectory.batches }}"
  run_once: yes

- name: Create batch run script
  template:
    src: run-batch.sh.j2
    dest: "{{ trajectory_dir}}/run-batch.sh"
    mode: 0755
  run_once: yes

- name: Create STRIDE VMD scripts
  template:
    src: sstructure.vmd.j2
    dest: "{{ trajectory_dir }}/analysis/sstructure{{ item.batch }}.vmd"
    mode: 0644
  loop: "{{ trajectory.batches }}"
  run_once: yes

- name: Create STRIDE run script
  template:
    src: run-stride.sh.j2
    dest: "{{ trajectory_dir}}/run-stride.sh"
    mode: 0755
  run_once: yes

- name: Create prod plot configs
  template:
    src: prod_plot.yaml.j2
    dest: "{{ trajectory_dir }}/analysis/prod_plot{{ item.batch }}.yaml"
    mode: 0644
  loop: "{{ trajectory.batches }}"
  run_once: yes

- name: Create prod plot script
  template:
    src: make_plots.sh.j2
    dest: "{{ trajectory_dir }}/make_plots.sh"
    mode: 0755
  run_once: yes

- name: Symlink preprod files
  file:
    src: "{{ preprod_dir }}/{{ item }}"
    dest: "{{ trajectory_dir }}/{{ item }}"
    state: link
  loop: "{{ preprod_files }}"
  run_once: yes
...
