---
- name: Setup the simulations
  hosts: aws
  vars:
    project_dir: /mdsim/project2
    cell_size: 35
    namd_cores: 16 #"{{ ansible_processor_nproc }}"
    preprod_files:
      - abf_solv.pdb
      - abf_solv.psf
      - abf_water_equil.coor
      - abf_solv_ions.pdb
      - abf_solv_ions.psf
      - abf_ibu_equil.coor
      - par_all36m_prot_ibu.prm
      - top_all36_prot_ibu.rtf
      - toppar_water_ions.str
    preprod_dir: "{{ project_dir }}/preprod"
  vars_files:
    - vars/sim_config.yaml
  tasks:

    - name: Configure ssh
      copy:
        dest: "/home/{{ ansible_user }}/.ssh/config"
        content: |
          Host github.com
            StrictHostKeyChecking no
        mode: 0600
      run_once: yes

    - name: Clone the md-simulations repo
      git:
        repo: git@github.com:ajsmith/md-simulations.git
        dest: "{{ project_dir }}/md-simulations"
      run_once: yes

    - name: Add directory for pre-production files
      file:
        path: "{{ preprod_dir }}"
        state: directory
        mode: 0755
      run_once: yes

    - name: Add pre-production files
      copy:
        src: "{{ item }}"
        dest: "{{ preprod_dir }}/{{ item }}"
        mode: 0644
      loop: "{{ preprod_files }}"
      run_once: yes

    - include_tasks: tasks/trajectory.yaml
      loop: "{{ simulation.trajectories }}"
      loop_control:
        loop_var: trajectory
      vars:
        trajectory_dir: "{{ project_dir }}/{{ trajectory.trajectory }}"
      run_once: yes

    - name: Create run-sim.sh script
      template:
        src: run-sim.sh.j2
        dest: "{{ project_dir }}/run-sim.sh"
        mode: 0755
      run_once: yes

    - name: Create run-analysis.sh script
      template:
        src: run-analysis.sh.j2
        dest: "{{ project_dir }}/run-analysis.sh"
        mode: 0755
      run_once: yes
...
